jobs:
  CloneRepo:
    resources:
      instance-type: C3
    uses: git-checkout@v1
    with:
      url: https://github.com/gradient-ai/mnist-sample.git
    outputs:
      mnist-sample:
        type: volume
  TrainModel:
    resources:
      instance-type: C3
    env:
      PS_MODEL_PATH: /my-trained-model
    uses: container@v1
    with:
      args:
        - bash
        - -c
        - >-
          cd /inputs/mnist-sample && python mnist.py
      image: tensorflow/tensorflow:1.15.5-py3
    needs:
      - CloneRepo
    inputs:
      mnist-sample: CloneRepo.outputs.mnist-sample
